### ISSUE TITLE
for Julia 0.4: rename to HTTPCommon

### ISSUE THREAD

**Issue by garborg** [JuliaWeb/HttpCommon.jl#18]
Make naming of 'HTTP' packages (HTTPClient.jl, HttpServer.jl, HttpParser.jl, and HttpCommon.jl) consistent. Timing to mirror timing of [rename of Color.jl](https://github.com/JuliaLang/Color.jl/issues/56) to Colors.jl, of [HttpServer.jl](https://github.com/JuliaWeb/HttpServer.jl/issues/43) to HTTPServer.jl, and of [HttpParser.jl](https://github.com/JuliaWeb/HttpParser.jl/issues/29) to HTTPParser.jl.

**Comment by IainNZ** [comment]
Closed in favour of https://github.com/JuliaWeb/Roadmap/issues/3
