### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by musm** [JuliaWeb/HttpCommon.jl#44]
Dep warns have been eliminated for 0.6 would be good to get  a release (last tag was May 16)

**Comment by musm** [comment]
bump

**Comment by tanmaykm** [comment]
Tagged https://github.com/JuliaWeb/HttpCommon.jl/releases/tag/v0.2.7.
Not sure why @attobot has not made the PR yet.
Maybe there's something wrong with the tag.
@tkelman ?

**Comment by tkelman** [comment]
Says it was enabled 3 months ago. @simonbyrne is the only one with access to the logs as far as I know. Don't know whether deleting the tag and trying again would overwrite the logs or anything.

**Comment by simonbyrne** [comment]
The problem is that it's just a tag, not a proper release: see instructions at https://github.com/attobot/attobot

**Comment by tanmaykm** [comment]
Thanks! That was it.
PR https://github.com/JuliaLang/METADATA.jl/pull/8404 made now.
