### ISSUE TITLE
TypeError on package precompilation on master

### ISSUE THREAD

**Issue by staticfloat** [JuliaWeb/HttpCommon.jl#48]
Nightly coverage runs are dying with:

```
ERROR: LoadError: TypeError: in Type{...} expression, expected UnionAll, got typeof(Base.Nullable)
Stacktrace:
 [1] top-level scope
 [2] include at ./boot.jl:283 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:503
 [4] include(::Module, ::String) at ./sysimg.jl:15
 [5] top-level scope
 [6] eval at ./boot.jl:286 [inlined]
 [7] top-level scope at ./<missing>:2
in expression starting at /home/buildworker/.julia/v0.7/HttpCommon/src/HttpCommon.jl:65
```

@kshyatt just notifying you so you know what's up with coverage right now

**Comment by ararslan** [comment]
I'm not familiar with what precisely the coverage buildbots run, but would it be possible to transition them to HTTP.jl?

**Comment by bluesmoon** [comment]
@ararslan there are two problems with switching to HTTP.jl.

   1. JuliaWeb/Requests.jl still uses HttpCommon.jl, so libraries using Requests.jl will still break
   2. There is no useful documentation for HTTP.jl

**Comment by quinnj** [comment]
[HTTP docs](https://juliaweb.github.io/HTTP.jl/stable/)?

**Comment by bluesmoon** [comment]
Thanks, these were quite useful, I managed to port my code from Requests to HTTP in about 10 minutes.

It would be good to have these linked from the repository description on github instead of just in the README.

**Comment by quinnj** [comment]
Great suggestion. Done!

**Comment by kshyatt** [comment]
Do we want to fix this package or transition to `HTTP.jl`?

**Comment by ararslan** [comment]
+1 for transitioning to HTTP

**Comment by quinnj** [comment]
The original issue here is fixed on master
