### ISSUE TITLE
Currently broken on 0.7

### ISSUE THREAD

**Issue by hustf** [JuliaWeb/HttpCommon.jl#49]
The PR #47 merged today fails tests due to changes on nightly made since November. I'd submit a PR as a follow-up, but I unfortunately have an issue compiling 0.7 locally. The travis logs point to the two lines that need a change.

**Comment by ararslan** [comment]
You could use the [nightly binaries](https://julialang.org/downloads/nightlies) for your system if you're unable to compile 0.7 from source.
