### ISSUE TITLE
Serve files in a streaming fashion

### ISSUE THREAD

**Issue by rened** [JuliaWeb/HttpCommon.jl#5]
Currently, `FileResponse()` loads the entire file and then constructs and returns a `Response` instance. This gets put on the wire in `HttpServer.write`. 

It would be better to have a streaming implementation of this. I would suggest

1. `Response` gets a `write` function which simply outputs the `Response.data`
2. `FileResponse()` only stores the data it needs to access the file
3. `Response/FileResponse.write()` get called in `HttpServer.write`
4. `FileResponse.write` reads from file and write to socket in a streaming fashion

It would not change the API, it would be a purely internal change.

Can I go ahead and work on a PR for this? Does anybody know of a good example for a good and solid (exception handling etc), Julianesque way of streaming read/write?

Thanks!

**Comment by IainNZ** [comment]
`FileResponse` has been moved to `HttpServer` (https://github.com/JuliaWeb/HttpServer.jl/pull/64), it was not a good fit for HttpCommon and everyone who needed it also was using HttpServer anyway.
